# Use a lightweight Java runtime
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy your built JAR file from the target folder
# Note: Ensure this matches the name generated by your maven-assembly-plugin
COPY target/backend-1.0-SNAPSHOT-jar-with-dependencies.jar app.jar

# Expose the port (Render will override this, but this is for reference)
EXPOSE 10000

# Command to run the application
ENTRYPOINT ["java", "-jar", "app.jar"]